Description: step function to update all provisioned products of a service catalog product to the latest version
Parameters:
  Environment:
    Description: the infrastructure environment
    Type: String
    Default: live
    AllowedValues:
      - test
      - live
  ListAccountsRoleArn:
    Description: ARN of an IAM role that can be assumed to call https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccounts.html
    Type: String
Resources:
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      RoleName: !Sub "${Environment}-sc-provisioned-product-updater-role"
      Policies:
        - PolicyName: state-machine-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Action:
                    - sts:AssumeRole
                  Resource:
                    - !Ref ListAccountsRoleArn
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Environment}-sc-product-updater-*"
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${Environment}-sc-provisioned-product-updater"
      RoleArn: !GetAtt StateMachineRole.Arn
      Definition:
        StartAt: DescribeProduct
        States:
          DescribeProduct:
            Type: Task
            Next: ListAccounts
            Resource: arn:aws:states:::lambda:invoke
            OutputPath: $.Payload
            Parameters:
              # despite the parameter being called FunctionName, it actually takes an ARN
              FunctionName: !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Environment}-sc-product-updater-get-latest-version"
              Payload:
                product_name.$: $$.Execution.Input.product_name
          ListAccounts:
            Type: Task
            End: true
            Resource: arn:aws:states:::aws-sdk:organizations:listAccounts
            Parameters: {}
            Credentials:
              RoleArn: !Ref ListAccountsRoleArn
